# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65f34609d3d12c4d347df68b41823c6ae8ea03e382c6a0b57c2073d65f35906e3ee1cdbec8fd6b998396c1c7393a8ee50424327caff400beec2a91991a4020a1

test:
  secret_key_base: ba6f8311a5796c7f73443aabd5d093abb425c56f0c26f5b7c4dcf9c0a0cf0c301a9b8fc21f6fa205c752f1b6062bc9ec6e299231210237999254534add182d21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
